title: My official log for GSoC 2020.
email: adityaborikar2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome page to keep track of weekly gsoc progress.
twitter_username: BorikarAditya
github_username:  adiaholic

theme: minima
plugins:
  - jekyll-feed
